Retrieve all books written by George Orwell.

sql
Copy
SELECT b.Title
FROM Books b
JOIN Authors a ON b.AuthorID = a.AuthorID
WHERE a.AuthorName = 'George Orwell';
Find the total revenue generated from all orders.

sql
Copy
SELECT SUM(b.Price * o.Quantity) AS TotalRevenue
FROM Orders o
JOIN Books b ON o.BookID = b.BookID;
List all books published before 1950.

sql
Copy
SELECT Title
FROM Books
WHERE PublishedYear < 1950;
Find the total number of books sold for each genre.

sql
Copy
SELECT b.Genre, SUM(o.Quantity) AS TotalSold
FROM Orders o
JOIN Books b ON o.BookID = b.BookID
GROUP BY b.Genre;
Retrieve the names of authors who have written more than one book.

sql
Copy
SELECT a.AuthorName
FROM Authors a
JOIN Books b ON a.AuthorID = b.AuthorID
GROUP BY a.AuthorName
HAVING COUNT(b.BookID) > 1;
Find the most expensive book in the database.

sql
Copy
SELECT Title, Price
FROM Books
ORDER BY Price DESC
LIMIT 1;
List all orders placed in the year 2023.

sql
Copy
SELECT o.OrderID, b.Title, o.Quantity, o.OrderDate
FROM Orders o
JOIN Books b ON o.BookID = b.BookID
WHERE YEAR(o.OrderDate) = 2023;
Find the average price of books in each genre.

sql
Copy
SELECT Genre, AVG(Price) AS AveragePrice
FROM Books
GROUP BY Genre;
Retrieve the total number of books ordered for each author.

sql
Copy
SELECT a.AuthorName, SUM(o.Quantity) AS TotalBooksOrdered
FROM Orders o
JOIN Books b ON o.BookID = b.BookID
JOIN Authors a ON b.AuthorID = a.AuthorID
GROUP BY a.AuthorName;
Find the book with the highest number of orders.

sql
Copy
SELECT b.Title, SUM(o.Quantity) AS TotalOrders
FROM Orders o
JOIN Books b ON o.BookID = b.BookID
GROUP BY b.Title
ORDER BY TotalOrders DESC
LIMIT 1;
Additional Queries for Practice
Here are a few more queries you can try:

List all authors and the number of books they have written.

sql
Copy
SELECT a.AuthorName, COUNT(b.BookID) AS NumberOfBooks
FROM Authors a
LEFT JOIN Books b ON a.AuthorID = b.AuthorID
GROUP BY a.AuthorName;
Find the total revenue generated by each author.

sql
Copy
SELECT a.AuthorName, SUM(b.Price * o.Quantity) AS TotalRevenue
FROM Orders o
JOIN Books b ON o.BookID = b.BookID
JOIN Authors a ON b.AuthorID = a.AuthorID
GROUP BY a.AuthorName;
List all books that have never been ordered.

sql
Copy
SELECT b.Title
FROM Books b
LEFT JOIN Orders o ON b.BookID = o.BookID
WHERE o.OrderID IS NULL;
Find the top 3 best-selling books.

sql
Copy
SELECT b.Title, SUM(o.Quantity) AS TotalSold
FROM Orders o
JOIN Books b ON o.BookID = b.BookID
GROUP BY b.Title
ORDER BY TotalSold DESC
LIMIT 3;
List all books along with their authors and genres.

sql
Copy
SELECT b.Title, a.AuthorName, b.Genre
FROM Books b
JOIN Authors a ON b.AuthorID = a.AuthorID;
